Legacy releases URL
aeternity/terraform-aws-mainnet-api pull request #26
Opened 2020-01-15 12:38 UTC by IvayloPapazov

close #23

2020-01-15 14:51 UTC, dincho approved these changes

2020-01-15 14:53 UTC, dincho requested changes
API gateway versions should be kept to 5.3.0 still.

But the legacy URL should be changed.

2020-01-15 15:20 UTC, IvayloPapazov commented
> API gateway versions should be kept to 5.3.0 still.

bba3fc1

2020-01-16 08:45 UTC, dincho submitted a review, later dismissed

2020-01-16 08:46 UTC, dincho commented
> > API gateway versions should be kept to 5.3.0 still.
> 
> [bba3fc1](https://github.com/aeternity/terraform-aws-mainnet-api/commit/bba3fc1c205a5fd68694f99013b83bfda643576a)

Ah, sorry it's 5.2.0 https://testnet.aeternity.io/v2/status

2020-01-16 12:22 UTC, dincho approved these changes

2020-01-18 18:06 UTC, venimus approved these changes

2020-01-27 11:02 UTC, merged